// Mocks generated by Mockito 5.4.5 from annotations
// in product_viewer/test/dashboard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:product_viewer/common/data/model/product_model.dart' as _i4;
import 'package:product_viewer/common/usecase/get_products_list_api_use_case.dart'
    as _i5;
import 'package:product_viewer/common/usecase/get_products_list_storage_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProductsListStorageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsListStorageUseCase extends _i1.Mock
    implements _i2.GetProductsListStorageUseCase {
  @override
  _i3.Future<List<_i4.ProductModel>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductModel>>.value(<_i4.ProductModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductModel>>.value(<_i4.ProductModel>[]),
      ) as _i3.Future<List<_i4.ProductModel>>);
}

/// A class which mocks [GetProductsListApiUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsListApiUseCase extends _i1.Mock
    implements _i5.GetProductsListApiUseCase {
  @override
  _i3.Future<List<_i4.ProductModel>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductModel>>.value(<_i4.ProductModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductModel>>.value(<_i4.ProductModel>[]),
      ) as _i3.Future<List<_i4.ProductModel>>);
}
