name: product_viewer
description: "Product Viewer sample."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10000000 #1 00 00 000


environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: 9.0.0

  # Network
  dio: 5.7.0                                  # https://pub.dev/packages/dio
  pretty_dio_logger: 1.4.0                    # https://pub.dev/packages/pretty_dio_logger

  # Data Structures
  freezed_annotation: 2.4.4                   # https://pub.dev/packages/freezed_annotation
  json_annotation: 4.9.0                      # https://pub.dev/packages/json_annotation

  # Logging
  talker: 4.4.7                               # https://pub.dev/packages/talker
  talker_flutter: 4.4.7                       # https://pub.dev/packages/talker_flutter
  talker_dio_logger: 4.4.7                    # https://pub.dev/packages/talker_dio_logger

  # Navigation
  auto_route: 9.3.0+1                         # https://pub.dev/packages/auto_route

  # Resources
  extended_image: 9.1.0                       # https://pub.dev/packages/extended_image
  flutter_native_splash: 2.4.4                # https://pub.dev/packages/flutter_native_splash
  intl: 0.19.0                                # https://pub.dev/packages/intl https://docs.flutter.dev/development/accessibility-and-localization/internationalization

  # UI
  flutter_animate: 4.5.2                      # https://pub.dev/packages/flutter_animate

  # Utility
  collection: 1.19.0                          # https://pub.dev/packages/collection


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Data Structures
  freezed: 2.5.7                              # https://pub.dev/packages/freezed
  json_serializable: 6.9.0                    # https://pub.dev/packages/json_serializable

  # Lint
  custom_lint: 0.7.0                          # https://pub.dev/packages/custom_lint
  flutter_lints: 5.0.0                        # https://pub.dev/packages/flutter_lints

  # Utils
  auto_route_generator: 9.0.0                 # https://pub.dev/packages/auto_route_generator
  build_runner: 2.4.14                        # https://pub.dev/packages/build_runner


flutter:
  uses-material-design: true
